@echo off
color 0f
echo UAU      (yes/no)
echo.
set /p uau=

if %uau% == yes goto uau
if %uau% == no goto sad

:uau
color 0a
cls
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU
echo UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU UAU

goto uau

:sad
color 0b
cls
echo me is SAD ;(
echo.
pause
exit